name: Python Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.11', '3.x']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools
        pip install graphviz numpy PyYAML
        pip install .

    - name: Run example.py
      run: python example.py

    - name: Upload stats output
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: stats-output-python-${{ matrix.python-version }}
        path: stats_out_2.txt
        if-no-files-found: warn
